name: Changelog

on:
  schedule:
    - cron: '0 15 * * *' # at 3am (it's in UTC)
  workflow_dispatch:

jobs:
  changelog:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: ⏬ Checkout code
        uses: actions/checkout@v3

      - name: 🔢 Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: ⏬ Install
        run: |
          npm install

      - name: 📰 Run LINZ Changelog script
        run: |
          mkdir -p data
          npm run changelog
        env:
          LINZ_API_KEY: ${{ secrets.LINZ_API_KEY }}
          GH_BASIC_AUTH: ${{ secrets.GH_BASIC_AUTH }}
