name: Sync

on:
  # temporarily disabled during topo50 import
  # schedule:
  #   - cron: '0 16 * * 1,5' # at 4pm on mon & fri UTC = at 4am on tue & sat NZST
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: ⏬ Checkout code
        uses: actions/checkout@v2

      - name: 🔢 Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: ⏬ Install
        run: |
          npm install

      - name: 🌏 Download planet file extract
        run: |
          yarn download-planet

      - name: 🥝 Download LINZ csv file
        run: |
          yarn download-linz

      - name: ⏩ Download list of addresses to ignore
        run: |
          yarn preprocess0

      - name: 🚚 Preprocess the .osm.pbf file
        run: |
          yarn preprocess1 --max-old-space-size=6144

      - name: 🚚 Preprocess the .csv file
        run: |
          yarn preprocess2 --max-old-space-size=6144

      - name: 🚚 Creates stacks from LINZ data
        run: |
          yarn preprocess3 --max-old-space-size=6144

      - name: 🔁 Conflate LINZ data with OSM
        run: |
          yarn conflate --max-old-space-size=6144

      - name: 🏡 Generate geojson and reports
        run: |
          yarn action --max-old-space-size=6144

      - name: ⛅ Upload geojson and reports to CDN
        run: |
          yarn upload --max-old-space-size=6144
        env:
          GH_BASIC_AUTH: ${{ secrets.GH_BASIC_AUTH }}
          AZ_CON: ${{ secrets.AZ_CON }}
